CREATE OR REPLACE TABLE "ETL_AF"."DEV_DB"."FACT_STOCK_GROUP1" (
    SYMBOL_ID NUMBER(38,0)
    ,COMPANY_ID NUMBER(38,0)
    ,DATE DATE
    ,OPEN NUMBER(18,8)
    ,HIGH NUMBER(18,8)
    ,LOW NUMBER(18,8)
    ,CLOSE NUMBER(18,8)
    ,VOLUME NUMBER(38,8)
    ,ADJCLOSE NUMBER(18,8));

CREATE OR REPLACE TABLE "ETL_AF"."DEV_DB"."DIM_STOCK_GROUP1" (
    ID	NUMBER(38,0)
    ,SYMBOL	VARCHAR(8)
    ,PRICE	NUMBER(18,8)
    ,BETA	NUMBER(18,8)
    ,VOLAVG	NUMBER(38,0)
    ,MKTCAP	NUMBER(38,0)
    ,LASTDIV	NUMBER(18,8)
    ,RANGE	VARCHAR(64)
    ,CHANGES	NUMBER(18,8)
    ,COMPANYNAME	VARCHAR(512)
    ,EXCHANGE	VARCHAR(64)
    ,INDUSTRY	VARCHAR(64)
    ,WEBSITE	VARCHAR(64)
    ,DESCRIPTION	VARCHAR(2048)
    ,CEO	VARCHAR(64)
    ,SECTOR	VARCHAR(64)
    ,DCFDIFF	NUMBER(18,8)
    ,DCF	NUMBER(18,8));

CREATE OR REPLACE TABLE "ETL_AF"."DEV_DB"."DIM2_STOCK_GROUP1"(
    ID	NUMBER(38,0)
    ,SYMBOL	VARCHAR(8)
    ,NAME VARCHAR
    , EXCHANGE VARCHAR
);

ALTER TABLE "ETL_AF"."DEV_DB"."FACT_STOCK_GROUP1" ADD PRIMARY KEY (SYMBOL_ID,COMPANY_ID,DATE);
ALTER TABLE "ETL_AF"."DEV_DB"."DIM_STOCK_GROUP1" ADD PRIMARY KEY (ID);
ALTER TABLE "ETL_AF"."DEV_DB"."DIM2_STOCK_GROUP1" ADD PRIMARY KEY (ID);
ALTER TABLE "ETL_AF"."DEV_DB"."FACT_STOCK_GROUP1" ADD FOREIGN KEY (COMPANY_ID) REFERENCES "ETL_AF"."DEV_DB"."DIM_STOCK_GROUP1"(ID);
ALTER TABLE "ETL_AF"."DEV_DB"."FACT_STOCK_GROUP1" ADD FOREIGN KEY (SYMBOL_ID) REFERENCES "ETL_AF"."DEV_DB"."DIM2_STOCK_GROUP1"(ID);