-- update and insert company profile data
MERGE INTO "ETL_AF"."DEV_DB"."DIM_COMPANY_PROFILE_GROUP2" AS P USING(
  SELECT 
    ID, 
    SYMBOL, 
    INDUSTRY, 
    WEBSITE, 
    DESCRIPTION, 
    CEO, 
    SECTOR 
    FROM "US_STOCKS_DAILY"."PUBLIC"."COMPANY_PROFILE"  
) AS T
  ON P.SYMBOL = T.SYMBOL
  WHEN MATCH THEN
   UPDATE SET P.ID, P.SYMBOL, P.INDUSTRY, P.WEBSITE, P.DESCRIPTION, P.CEO, P.SECTOR
  WHEN NOT MATCHED THEN 
    INSERT (P.ID, P.SYMBOL, P.INDUSTRY, P.WEBSITE, P.DESCRIPTION, P.CEO, P.SECTOR) 
    VALUES (T.ID, T.SYMBOL, T.INDUSTRY, T.WEBSITE, T.DESCRIPTION, T.CEO, P.SECTOR);
    
    
