-- update and insert company profile data
MERGE INTO "ETL_AF"."DEV_DB"."DIM_COMPANY_PROFILE_GROUP2" AS P USING(
  SELECT 
    ID, 
    SYMBOL, 
    NAME,
    INDUSTRY, 
    EXCHANGE,
    WEBSITE, 
    DESCRIPTION, 
    CEO, 
    SECTOR 
    FROM "US_STOCKS_DAILY"."PUBLIC"."COMPANY_PROFILE"  
) AS T
  ON P.SYMBOL = T.SYMBOL
  WHEN MATCHED THEN
   UPDATE SET P.ID=T.ID, P.SYMBOL=T.SYMBOL, P.NAME=T.NAME, P.INDUSTRY=T.INDUSTRY, P.EXCHANGE=T.EXCHANGE, P.WEBSITE=T.WEBSITE, P.DESCRIPTION=T.DESCRIPTION, P.CEO=T.CEO, P.SECTOR=T.SECTOR
  WHEN NOT MATCHED THEN 
    INSERT (P.ID, P.SYMBOL, P.NAME, P.INDUSTRY, P.EXCHANGE, P.WEBSITE, P.DESCRIPTION, P.CEO, P.SECTOR) 
    VALUES (T.ID, T.SYMBOL, T.NAME, T.INDUSTRY, T.EXCHANGE, T.WEBSITE, T.DESCRIPTION, T.CEO, T.SECTOR);
    
    
