CREATE OR REPLACE TABLE "ETL_AF"."DEV_DB".prestage_sales_group2(
    ORDERNUMBER INT,
    QUANTITYORDERED INT,
    PRICEEACH FLOAT,
    SALES FLOAT,
    ORDERDATE DATETIME,
    YEAR_ID INT,
    CUSTOMERNAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    COUNTRY VARCHAR
);
