-- ONLY INSERT THE DATA THAT'S NOT IN FACT TABLE
INSERT INTO "ETL_AF"."DEV_DB"."FACT_STOCK_GROUP1"
-- FILTER DATA BY ID AND DATE
WITH NEW_ENTRY AS
(SELECT 
    * 
 FROM "US_STOCKS_DAILY"."PUBLIC"."STOCK_HISTORY"
 WHERE (ID, DATE) NOT IN (SELECT 
                            ID
                            ,DATE
                          FROM "ETL_AF"."DEV_DB"."FACT_STOCK_GROUP1"))
-- FIND CORRESPONDING ID BASED ON SYMBOLS IN THE SYMBOLS TABLE
SELECT 
    S.ID AS ID
    ,DATE
    ,OPEN
    ,HIGH
    ,LOW
    ,CLOSE
    ,VOLUME
    ,ADJCLOSE
 FROM NEW_ENTRY T
 JOIN "US_STOCKS_DAILY"."PUBLIC"."SYMBOLS" S 
 ON T.SYMBOL = S.SYMBOL;

-- Insert data into the dimension table in the same way
INSERT INTO "ETL_AF"."DEV_DB"."DIM_STOCK_GROUP1"
SELECT * FROM "US_STOCKS_DAILY"."PUBLIC"."COMPANY_PROFILE"
WHERE ID NOT IN (SELECT ID FROM "ETL_AF"."DEV_DB"."DIM_STOCK_GROUP1");
